# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a958b7e1eaf00fa9e2b5cf59d965dd199b8d3a6bb4b2c1d0c0d3bed64926a409abd44e899329b132aad156f0b7f1301600c2057aa608cc761e15a4ecdef7e327

test:
  secret_key_base: 4acd43d4dae631465da88350b6bdd5bd08dbb49732c5b54a7e0595fc85972588876b04de94cc6833666ab38d728e801984d9b75bc0c7edec20e58a193c4e48a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
